name: tests_octave

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install octave
      run: |
        sudo apt-get update
        sudo apt-get install octave
    - name: Test
      run: |
        cd matlab_octave
        octave toy_example.m
